config/routes.rb
Rails.application.routes.draw do

  root to: 'public/pages#home'

  namespace :public do
    get 'pages/show/:page' => "pages#show", as: 'pages'
    get 'pages/about'
    get 'pages/error'
    get 'pages/home'
  end

  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout", as: 'logout'

  resources :cogs
  resources :widgets
  resources :agencies
  resources :contacts
  get "/contacts/search", to: 'contacts#search', as: 'search'
  get "/pages/error", to: 'pages#error', as: 'error'
  get "/pages/:page"   => "pages#show", as: 'pages'
  get "/dashboards/:dashboard" => "dashboards#show", as: 'dashboards'
end

app/models/agency.rb
class Agency < ApplicationRecord
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

  include Secured # see concerns

  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:name, :status, :state, :logo)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_with(model: agency, local: true) do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :agency_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :agency_status %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.check_box :state, id: :agency_state %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_field :logo, id: :agency_logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>State</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each do |agency| %>
      <tr>
        <td><%= agency.name %></td>
        <td><%= agency.status %></td>
        <td><%= agency.state %></td>
        <td><%= agency.logo %></td>
        <td><%= link_to 'Show', agency %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @agency.status %>
</p>

<p>
  <strong>State:</strong>
  <%= @agency.state %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @agency.logo %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>