config/routes.rb
Rails.application.routes.draw do

  root to: 'public/pages#home'

  namespace :public do
    get 'pages/show/:page' => "pages#show", as: 'pages'
    get 'pages/about'
    get 'pages/error'
    get 'pages/home'
  end

  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout", as: 'logout'

  resources :cogs
  resources :widgets
  resources :agencies
  resources :contacts
  get "/contacts/search", to: 'contacts#search', as: 'search'
  get "/pages/error", to: 'pages#error', as: 'error'
  get "/pages/:page"   => "pages#show", as: 'pages'
  get "/dashboards/:dashboard" => "dashboards#show", as: 'dashboards'
end

app/models/cog.rb
class Cog < ApplicationRecord
end

app/controllers/cogs_controller.rb
class CogsController < ApplicationController
  before_action :set_cog, only: [:show, :edit, :update, :destroy]

  # GET /cogs
  # GET /cogs.json
  def index
    @cogs = Cog.all
  end

  # GET /cogs/1
  # GET /cogs/1.json
  def show
  end

  # GET /cogs/new
  def new
    @cog = Cog.new
  end

  # GET /cogs/1/edit
  def edit
  end

  # POST /cogs
  # POST /cogs.json
  def create
    @cog = Cog.new(cog_params)

    respond_to do |format|
      if @cog.save
        format.html { redirect_to @cog, notice: 'Cog was successfully created.' }
        format.json { render :show, status: :created, location: @cog }
      else
        format.html { render :new }
        format.json { render json: @cog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cogs/1
  # PATCH/PUT /cogs/1.json
  def update
    respond_to do |format|
      if @cog.update(cog_params)
        format.html { redirect_to @cog, notice: 'Cog was successfully updated.' }
        format.json { render :show, status: :ok, location: @cog }
      else
        format.html { render :edit }
        format.json { render json: @cog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cogs/1
  # DELETE /cogs/1.json
  def destroy
    @cog.destroy
    respond_to do |format|
      format.html { redirect_to cogs_url, notice: 'Cog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cog
      @cog = Cog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cog_params
      params.require(:cog).permit(:name, :size, :color)
    end
end

app/helpers/cogs_helper.rb
module CogsHelper
end

app/views/cogs/_form.html.erb
<%= form_with(model: cog, local: true) do |form| %>
  <% if cog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cog.errors.count, "error") %> prohibited this cog from being saved:</h2>

      <ul>
      <% cog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cog_name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :cog_size %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :cog_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cogs/edit.html.erb
<h1>Editing Cog</h1>

<%= render 'form', cog: @cog %>

<%= link_to 'Show', @cog %> |
<%= link_to 'Back', cogs_path %>

app/views/cogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cogs.each do |cog| %>
      <tr>
        <td><%= cog.name %></td>
        <td><%= cog.size %></td>
        <td><%= cog.color %></td>
        <td><%= link_to 'Show', cog %></td>
        <td><%= link_to 'Edit', edit_cog_path(cog) %></td>
        <td><%= link_to 'Destroy', cog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cog', new_cog_path %>

app/views/cogs/new.html.erb
<h1>New Cog</h1>

<%= render 'form', cog: @cog %>

<%= link_to 'Back', cogs_path %>

app/views/cogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cog.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @cog.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cog.color %>
</p>

<%= link_to 'Edit', edit_cog_path(@cog) %> |
<%= link_to 'Back', cogs_path %>