config/routes.rb
Rails.application.routes.draw do

  root to: 'public/pages#home'

  namespace :public do
    get 'pages/show/:page' => "pages#show", as: 'pages'
    get 'pages/about'
    get 'pages/error'
    get 'pages/home'
  end

  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout", as: 'logout'

  resources :cogs
  resources :widgets
  resources :agencies
  resources :contacts
  get "/contacts/search", to: 'contacts#search', as: 'search'
  get "/pages/error", to: 'pages#error', as: 'error'
  get "/pages/:page"   => "pages#show", as: 'pages'
  get "/dashboards/:dashboard" => "dashboards#show", as: 'dashboards'
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to "Assign2018 [#{Rails.env[0..2]}]", pages_path('about'), class:"navbar-brand" %>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if @page == 'about' %>">
          <%= link_to 'About', pages_path('about'), class:"nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if @page == 'settings' %>">
          <%= link_to 'Settings', pages_path('settings'), class:"nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if @page == 'profile' %>">
          <%= link_to 'Profile', pages_path('profile'), class:"nav-link" %>
        </li>
      </ul>

      <%= form_tag(search_path, method: "get", class:"form-inline mt-2 mt-md-0") do %>
        <%= text_field_tag(:q, nil, placeholder: "Search", class: 'form-control mr-sm-2') %>
        <%= submit_tag("Search", class:"btn btn-outline-success my-2 my-sm-0") %>
      <% end %>

      <div class="nav-item" >
          <%= link_to 'Logout', logout_path, class:"nav-link" %>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <% active = @dashboard == 'analytics' ? 'nav-active' : '' %>
      <%-# the display name to the user does not match the internal name -%>
      <%= link_to dashboards_path('analytics'), class:"nav-link #{active}" do %>
        <span class="glyphicon glyphicon-euro"></span> Charts
      <% end %>

    </li>
    <li class="nav-item">
      <% active = @dashboard == 'reports' ? 'nav-active' : '' %>
      <%= link_to 'Statistics', dashboards_path('reports'), class:"nav-link #{active}" %>
    </li>
    <li class="nav-item">
      <% active = @dashboard == 'exports' ? 'nav-active' : '' %>
      <%= link_to 'Exports', dashboards_path('exports'), class:"nav-link #{active}" %>
    </li>
  </ul>

  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Section I <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <% active = current_page?(controller: 'cogs', action: 'index') ? 'nav-active' : '' %>
      <%= link_to 'Cogs...', cogs_path, class:"nav-link #{active}" %>
    </li>
    <li class="nav-item">
      <% active = current_page?(controller: 'agencies', action: 'index') ? 'nav-active' : '' %>
      <%= link_to 'Agency...', agencies_path, class:"nav-link #{active}" %>
    </li>

    <li class="nav-item">
      <% active = current_page?(controller: 'widgets', action: 'index') ? 'nav-active' : '' %>
      <%= link_to 'Widgets...', widgets_path, class:"nav-link #{active}" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Admins</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Users</a>
    </li>
  </ul>

  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link active" href="#">Section II <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Nav item again</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">One more nav</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Another nav item</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assign2018 [<%= Rails.env[0..2] %>]</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <%= render 'layouts/sidebar' %>
        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>